[package]
name = "dynamic_value"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/mdz-technology/dynamic_value"
license-file = "LICENSE"

[lib]
name = "dynamic_value"
path = "src/lib.rs"
# generate to library compatible with C
crate-type = ["rlib", "cdylib"] # Configuración opcional para crear librerías compartidas

[dependencies]
serde_json = "1.0.140"
uuid = { version = "1.11.0", features = ["v4"] }
thiserror = "1.0"
